### ISSUE TITLE
Create Docker HUB Repository

### ISSUE THREAD

**Issue by ghophp** [leogregianin/brcep#17]
In order to have an easy way to distribute the project, let's create a Docker HUB repository and link to the repository, it will automatically build based on the Dockerfile present in the repository.

**Comment by ghophp** [comment]
I think this one you should do @leogregianin not tag as hacktoberfest.. since you are the owner of the repo.. you can easily do it by logging in to docker.hub and link you github account, then you will be able to see this repo when creating the repository for the docker image.

**Comment by leogregianin** [comment]
Created image for DockerHub https://cloud.docker.com/repository/docker/leogregianin/brcep

**Comment by ghophp** [comment]
cool.. if you add me as a contributor to the docker hub repository I can push the first image and open a PR tomorrow providing an example on the README how to use docker run to run the image directly, making the first execution of the project very friendly.

**Comment by ghophp** [comment]
here is an example https://github.com/ghophp/buildbot-dashboard#running-with-docker of what I mean

**Comment by leogregianin** [comment]
Created https://hub.docker.com/r/leogregianin/brcep
