### ISSUE TITLE
Fix linter

### ISSUE THREAD

**Issue by leogregianin** [leogregianin/brcep#23]
Fix problems detected by golint

https://goreportcard.com/report/github.com/leogregianin/brcep#golint

**Comment by ellisonleao** [comment]
i can take this one

**Comment by vdepatla** [comment]
@leogregianin @ellisonleao jus created a PR for this

**Comment by vdepatla** [comment]
https://github.com/leogregianin/brcep/pull/26

**Comment by ellisonleao** [comment]
Cool! thanks @vdepatla

**Comment by leogregianin** [comment]
Thanks @vdepatla and @ellisonleao
